### ISSUE TITLE
.i e'o fau lenu sisku tu'a le tordu na'e traji lujvo kei goi ko'a le proga cu sisku tu'a le tordu je'a traji

### ISSUE THREAD

**Issue by mattfbacon** [lynn/lidysisku#12]
.i da'i plixau falenu tordygau gi'e za'ure'u sisku vau fau ko'a
.i fu'e mu'a .i le pilno cu sisku tu'a zo balckule .i ri na'e zasti be du'o la jbovlaste .i ku'i zo balcu'e je'a go'i .i da'i plixau falenu la lidysisku cu zmiku sisku tu'a zo balcu'e ji'a noi jai ja'e tordygau zo balckule .i fu'o
.i pe'i mi ka'eda'i zbasu faulenu do djica

**Comment by lynn** [comment]
.i .u'a ca co'e :) 

![image](https://github.com/lynn/lidysisku/assets/16232127/21d76a02-71cb-4940-973f-fcae4f5644f0)

**Comment by mattfbacon** [comment]
ki'esai finti be lo zabna
